// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE50JjT1DdFPn1MvRsmJMRZlLP3dg5YeA',
    appId: '1:1058132185559:web:f77c21749f272eb64dbb92',
    messagingSenderId: '1058132185559',
    projectId: 'cmsc23-final-project',
    authDomain: 'cmsc23-final-project.firebaseapp.com',
    storageBucket: 'cmsc23-final-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCNHHvBp7TL1DUNgRfxMgBKRxhhVDAmtU',
    appId: '1:1058132185559:android:cb2fb9e48df3d3604dbb92',
    messagingSenderId: '1058132185559',
    projectId: 'cmsc23-final-project',
    storageBucket: 'cmsc23-final-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0lrw8cZNK1VR6UbH9eDrfJCr1wie8qYk',
    appId: '1:1058132185559:ios:f55957ab7aeb4e7e4dbb92',
    messagingSenderId: '1058132185559',
    projectId: 'cmsc23-final-project',
    storageBucket: 'cmsc23-final-project.appspot.com',
    iosClientId: '1058132185559-1fltf2g7nvqgp8cb3hhcgvijaafs27gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0lrw8cZNK1VR6UbH9eDrfJCr1wie8qYk',
    appId: '1:1058132185559:ios:f55957ab7aeb4e7e4dbb92',
    messagingSenderId: '1058132185559',
    projectId: 'cmsc23-final-project',
    storageBucket: 'cmsc23-final-project.appspot.com',
    iosClientId: '1058132185559-1fltf2g7nvqgp8cb3hhcgvijaafs27gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
